### ISSUE TITLE
"Not Acceptible!" error

### ISSUE THREAD

**Issue by HunterZ** [xmunoz/bugzilla2gitlab#49]
Getting the following error from the Bugzilla server when trying to run this:
```
Loading user cache...
Loading milestone cache...
Traceback (most recent call last):
  File "/home/x/projects/bugzilla2gitlab/venv/bin/bugzilla2gitlab", line 26, in <module>
    main()
  File "/home/x/projects/bugzilla2gitlab/venv/bin/bugzilla2gitlab", line 23, in main
    client.migrate(bugs)
  File "/home/x/projects/bugzilla2gitlab/venv/lib64/python3.11/site-packages/bugzilla2gitlab/migrator.py", line 16, in migrate
    bugzilla_login(
  File "/home/x/projects/bugzilla2gitlab/venv/lib64/python3.11/site-packages/bugzilla2gitlab/utils.py", line 123, in bugzilla_login
    _perform_request(login_url, "get", json=False)
  File "/home/x/projects/bugzilla2gitlab/venv/lib64/python3.11/site-packages/bugzilla2gitlab/utils.py", line 46, in _perform_request
    raise Exception(
Exception: 406 failed requests: [Not Acceptable] Response: [b'<head><title>Not Acceptable!</title></head><body><h1>Not Acceptable!</h1><p>An appropriate representation of the requested resource could not be found on this server. This error was generated by Mod_Security.</p></body></html>'] Request data: [{}] Url: [http://abc.xyz.com/bugzilla/index.cgi] Headers: [{}]
```

**Comment by HunterZ** [comment]
Added a user agent to the header, and now I'm getting 401 Unauthorized from gitlab.com when trying to read milestones.

**Comment by HunterZ** [comment]
Okay, the ultimate fix was to modify `_perform_request()` in utils.py to set the user agent there, because trying to set it in the config file apparently stomps the private token:
```py
    headers["User-Agent"] = "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0"
```
